In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('C:\\Users\\Junaid Ahmed\\Downloads\\Fortune1000.csv')
df

,name,industry,sector,website,rank
0,Walmart,General Merchandisers,Retailing,http://www.walmart.com,1
1,Exxon Mobil,Petroleum Refining,Energy,http://www.exxonmobil.com,NaN
2,NaN,Petroleum Refining,Energy,http://www.chevron.com,NaN
3,NaN,Insurance: Property and Casualty (Stock),Financials,http://www.berkshirehathaway.com,1
4,Apple,"Computers, Office Equipment",Technology,http://www.apple.com,1
5,General Motors,Motor Vehicles and Parts,Motor Vehicles & Parts,http://www.gm.com,1
6,Phillips 66,Petroleum Refining,Energy,http://www.phillips66.com,1
7,General Electric,Diversified Financials,Financials,http://www.ge.com,8
8,Ford Motor,Motor Vehicles and Parts,Motor Vehicles & Parts,http://www.ford.com,9
9,CVS Health,CVS Health,CVS Health,CVS Health,CVS Health

In [4]:
df.replace(to_replace='Energy' ,value='light')

,name,industry,sector,website,rank
0,Walmart,General Merchandisers,Retailing,http://www.walmart.com,1
1,Exxon Mobil,Petroleum Refining,light,http://www.exxonmobil.com,NaN
2,NaN,Petroleum Refining,light,http://www.chevron.com,NaN
3,NaN,Insurance: Property and Casualty (Stock),Financials,http://www.berkshirehathaway.com,1
4,Apple,"Computers, Office Equipment",Technology,http://www.apple.com,1
5,General Motors,Motor Vehicles and Parts,Motor Vehicles & Parts,http://www.gm.com,1
6,Phillips 66,Petroleum Refining,light,http://www.phillips66.com,1
7,General Electric,Diversified Financials,Financials,http://www.ge.com,8
8,Ford Motor,Motor Vehicles and Parts,Motor Vehicles & Parts,http://www.ford.com,9
9,CVS Health,CVS Health,CVS Health,CVS Health,CVS Health

In [5]:
df.replace('Energy' ,'light')

,name,industry,sector,website,rank
0,Walmart,General Merchandisers,Retailing,http://www.walmart.com,1
1,Exxon Mobil,Petroleum Refining,light,http://www.exxonmobil.com,NaN
2,NaN,Petroleum Refining,light,http://www.chevron.com,NaN
3,NaN,Insurance: Property and Casualty (Stock),Financials,http://www.berkshirehathaway.com,1
4,Apple,"Computers, Office Equipment",Technology,http://www.apple.com,1
5,General Motors,Motor Vehicles and Parts,Motor Vehicles & Parts,http://www.gm.com,1
6,Phillips 66,Petroleum Refining,light,http://www.phillips66.com,1
7,General Electric,Diversified Financials,Financials,http://www.ge.com,8
8,Ford Motor,Motor Vehicles and Parts,Motor Vehicles & Parts,http://www.ford.com,9
9,CVS Health,CVS Health,CVS Health,CVS Health,CVS Health

In [7]:
df.replace(1,10)

,name,industry,sector,website,rank
0,Walmart,General Merchandisers,Retailing,http://www.walmart.com,1
1,Exxon Mobil,Petroleum Refining,Energy,http://www.exxonmobil.com,NaN
2,NaN,Petroleum Refining,Energy,http://www.chevron.com,NaN
3,NaN,Insurance: Property and Casualty (Stock),Financials,http://www.berkshirehathaway.com,1
4,Apple,"Computers, Office Equipment",Technology,http://www.apple.com,1
5,General Motors,Motor Vehicles and Parts,Motor Vehicles & Parts,http://www.gm.com,1
6,Phillips 66,Petroleum Refining,Energy,http://www.phillips66.com,1
7,General Electric,Diversified Financials,Financials,http://www.ge.com,8
8,Ford Motor,Motor Vehicles and Parts,Motor Vehicles & Parts,http://www.ford.com,9
9,CVS Health,CVS Health,CVS Health,CVS Health,CVS Health

In [8]:
df.replace(['Walmart','Exxon Mobil','NaN'],['good','bad','bad'])

,name,industry,sector,website,rank
0,good,General Merchandisers,Retailing,http://www.walmart.com,1
1,bad,Petroleum Refining,Energy,http://www.exxonmobil.com,NaN
2,NaN,Petroleum Refining,Energy,http://www.chevron.com,NaN
3,NaN,Insurance: Property and Casualty (Stock),Financials,http://www.berkshirehathaway.com,1
4,Apple,"Computers, Office Equipment",Technology,http://www.apple.com,1
5,General Motors,Motor Vehicles and Parts,Motor Vehicles & Parts,http://www.gm.com,1
6,Phillips 66,Petroleum Refining,Energy,http://www.phillips66.com,1
7,General Electric,Diversified Financials,Financials,http://www.ge.com,8
8,Ford Motor,Motor Vehicles and Parts,Motor Vehicles & Parts,http://www.ford.com,9
9,CVS Health,CVS Health,CVS Health,CVS Health,CVS Health

In [9]:
df.replace({'sector':'light'},'Energy')

,name,industry,sector,website,rank
0,Walmart,General Merchandisers,Retailing,http://www.walmart.com,1
1,Exxon Mobil,Petroleum Refining,Energy,http://www.exxonmobil.com,NaN
2,NaN,Petroleum Refining,Energy,http://www.chevron.com,NaN
3,NaN,Insurance: Property and Casualty (Stock),Financials,http://www.berkshirehathaway.com,1
4,Apple,"Computers, Office Equipment",Technology,http://www.apple.com,1
5,General Motors,Motor Vehicles and Parts,Motor Vehicles & Parts,http://www.gm.com,1
6,Phillips 66,Petroleum Refining,Energy,http://www.phillips66.com,1
7,General Electric,Diversified Financials,Financials,http://www.ge.com,8
8,Ford Motor,Motor Vehicles and Parts,Motor Vehicles & Parts,http://www.ford.com,9
9,CVS Health,CVS Health,CVS Health,CVS Health,CVS Health

In [12]:
df.replace({'sector':'light','rank':'1'},'none')

,name,industry,sector,website,rank
0,Walmart,General Merchandisers,Retailing,http://www.walmart.com,none
1,Exxon Mobil,Petroleum Refining,Energy,http://www.exxonmobil.com,NaN
2,NaN,Petroleum Refining,Energy,http://www.chevron.com,NaN
3,NaN,Insurance: Property and Casualty (Stock),Financials,http://www.berkshirehathaway.com,none
4,Apple,"Computers, Office Equipment",Technology,http://www.apple.com,none
5,General Motors,Motor Vehicles and Parts,Motor Vehicles & Parts,http://www.gm.com,none
6,Phillips 66,Petroleum Refining,Energy,http://www.phillips66.com,none
7,General Electric,Diversified Financials,Financials,http://www.ge.com,8
8,Ford Motor,Motor Vehicles and Parts,Motor Vehicles & Parts,http://www.ford.com,9
9,CVS Health,CVS Health,CVS Health,CVS Health,CVS Health

In [14]:
df.replace('[A-Za-z]',0)

,name,industry,sector,website,rank
0,Walmart,General Merchandisers,Retailing,http://www.walmart.com,1
1,Exxon Mobil,Petroleum Refining,Energy,http://www.exxonmobil.com,NaN
2,NaN,Petroleum Refining,Energy,http://www.chevron.com,NaN
3,NaN,Insurance: Property and Casualty (Stock),Financials,http://www.berkshirehathaway.com,1
4,Apple,"Computers, Office Equipment",Technology,http://www.apple.com,1
5,General Motors,Motor Vehicles and Parts,Motor Vehicles & Parts,http://www.gm.com,1
6,Phillips 66,Petroleum Refining,Energy,http://www.phillips66.com,1
7,General Electric,Diversified Financials,Financials,http://www.ge.com,8
8,Ford Motor,Motor Vehicles and Parts,Motor Vehicles & Parts,http://www.ford.com,9
9,CVS Health,CVS Health,CVS Health,CVS Health,CVS Health

In [15]:
df.replace('[A-Za-z]',0,regex=True)

   name  industry  sector  website rank
0   0.0         0       0        0    1
1   0.0         0       0        0  NaN
2   NaN         0       0        0  NaN
3   NaN         0       0        0    1
4   0.0         0       0        0    1
5   0.0         0       0        0    1
6   0.0         0       0        0    1
7   0.0         0       0        0    8
8   0.0         0       0        0    9
9   0.0         0       0        0    0

In [16]:
df.replace({'industry':'[A-Za-z]'},0,regex=True)

,name,industry,sector,website,rank
0,Walmart,0,Retailing,http://www.walmart.com,1
1,Exxon Mobil,0,Energy,http://www.exxonmobil.com,NaN
2,NaN,0,Energy,http://www.chevron.com,NaN
3,NaN,0,Financials,http://www.berkshirehathaway.com,1
4,Apple,0,Technology,http://www.apple.com,1
5,General Motors,0,Motor Vehicles & Parts,http://www.gm.com,1
6,Phillips 66,0,Energy,http://www.phillips66.com,1
7,General Electric,0,Financials,http://www.ge.com,8
8,Ford Motor,0,Motor Vehicles & Parts,http://www.ford.com,9
9,CVS Health,0,CVS Health,CVS Health,CVS Health

In [17]:
df.replace('Energy', method='ffill')

,name,industry,sector,website,rank
0,Walmart,General Merchandisers,Retailing,http://www.walmart.com,1
1,Exxon Mobil,Petroleum Refining,Retailing,http://www.exxonmobil.com,NaN
2,NaN,Petroleum Refining,Retailing,http://www.chevron.com,NaN
3,NaN,Insurance: Property and Casualty (Stock),Financials,http://www.berkshirehathaway.com,1
4,Apple,"Computers, Office Equipment",Technology,http://www.apple.com,1
5,General Motors,Motor Vehicles and Parts,Motor Vehicles & Parts,http://www.gm.com,1
6,Phillips 66,Petroleum Refining,Motor Vehicles & Parts,http://www.phillips66.com,1
7,General Electric,Diversified Financials,Financials,http://www.ge.com,8
8,Ford Motor,Motor Vehicles and Parts,Motor Vehicles & Parts,http://www.ford.com,9
9,CVS Health,CVS Health,CVS Health,CVS Health,CVS Health

In [18]:
df.replace('Energy', method='bfill')

,name,industry,sector,website,rank
0,Walmart,General Merchandisers,Retailing,http://www.walmart.com,1
1,Exxon Mobil,Petroleum Refining,Financials,http://www.exxonmobil.com,NaN
2,NaN,Petroleum Refining,Financials,http://www.chevron.com,NaN
3,NaN,Insurance: Property and Casualty (Stock),Financials,http://www.berkshirehathaway.com,1
4,Apple,"Computers, Office Equipment",Technology,http://www.apple.com,1
5,General Motors,Motor Vehicles and Parts,Motor Vehicles & Parts,http://www.gm.com,1
6,Phillips 66,Petroleum Refining,Financials,http://www.phillips66.com,1
7,General Electric,Diversified Financials,Financials,http://www.ge.com,8
8,Ford Motor,Motor Vehicles and Parts,Motor Vehicles & Parts,http://www.ford.com,9
9,CVS Health,CVS Health,CVS Health,CVS Health,CVS Health

In [20]:
df.replace('1',method='bfill', limit=1)

,name,industry,sector,website,rank
0,Walmart,General Merchandisers,Retailing,http://www.walmart.com,NaN
1,Exxon Mobil,Petroleum Refining,Energy,http://www.exxonmobil.com,NaN
2,NaN,Petroleum Refining,Energy,http://www.chevron.com,NaN
3,NaN,Insurance: Property and Casualty (Stock),Financials,http://www.berkshirehathaway.com,1
4,Apple,"Computers, Office Equipment",Technology,http://www.apple.com,1
5,General Motors,Motor Vehicles and Parts,Motor Vehicles & Parts,http://www.gm.com,1
6,Phillips 66,Petroleum Refining,Energy,http://www.phillips66.com,8
7,General Electric,Diversified Financials,Financials,http://www.ge.com,8
8,Ford Motor,Motor Vehicles and Parts,Motor Vehicles & Parts,http://www.ford.com,9
9,CVS Health,CVS Health,CVS Health,CVS Health,CVS Health

In [21]:
df

,name,industry,sector,website,rank
0,Walmart,General Merchandisers,Retailing,http://www.walmart.com,1
1,Exxon Mobil,Petroleum Refining,Energy,http://www.exxonmobil.com,NaN
2,NaN,Petroleum Refining,Energy,http://www.chevron.com,NaN
3,NaN,Insurance: Property and Casualty (Stock),Financials,http://www.berkshirehathaway.com,1
4,Apple,"Computers, Office Equipment",Technology,http://www.apple.com,1
5,General Motors,Motor Vehicles and Parts,Motor Vehicles & Parts,http://www.gm.com,1
6,Phillips 66,Petroleum Refining,Energy,http://www.phillips66.com,1
7,General Electric,Diversified Financials,Financials,http://www.ge.com,8
8,Ford Motor,Motor Vehicles and Parts,Motor Vehicles & Parts,http://www.ford.com,9
9,CVS Health,CVS Health,CVS Health,CVS Health,CVS Health

In [22]:
df.replace('1','100',inplace=True)

In [23]:
df

,name,industry,sector,website,rank
0,Walmart,General Merchandisers,Retailing,http://www.walmart.com,100
1,Exxon Mobil,Petroleum Refining,Energy,http://www.exxonmobil.com,NaN
2,NaN,Petroleum Refining,Energy,http://www.chevron.com,NaN
3,NaN,Insurance: Property and Casualty (Stock),Financials,http://www.berkshirehathaway.com,100
4,Apple,"Computers, Office Equipment",Technology,http://www.apple.com,100
5,General Motors,Motor Vehicles and Parts,Motor Vehicles & Parts,http://www.gm.com,100
6,Phillips 66,Petroleum Refining,Energy,http://www.phillips66.com,100
7,General Electric,Diversified Financials,Financials,http://www.ge.com,8
8,Ford Motor,Motor Vehicles and Parts,Motor Vehicles & Parts,http://www.ford.com,9
9,CVS Health,CVS Health,CVS Health,CVS Health,CVS Health