In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('C:\\Users\\Junaid Ahmed\\Downloads\\Fortune1000.csv')
df

,name,industry,sector,website,rank
0,Walmart,General Merchandisers,Retailing,http://www.walmart.com,1
1,Exxon Mobil,Petroleum Refining,Energy,http://www.exxonmobil.com,NaN
2,NaN,Petroleum Refining,Energy,http://www.chevron.com,NaN
3,NaN,Insurance: Property and Casualty (Stock),Financials,http://www.berkshirehathaway.com,1
4,Apple,"Computers, Office Equipment",Technology,http://www.apple.com,1
5,General Motors,Motor Vehicles and Parts,Motor Vehicles & Parts,http://www.gm.com,1
6,Phillips 66,Petroleum Refining,Energy,http://www.phillips66.com,1
7,General Electric,Diversified Financials,Financials,http://www.ge.com,8
8,Ford Motor,Motor Vehicles and Parts,Motor Vehicles & Parts,http://www.ford.com,9
9,CVS Health,CVS Health,CVS Health,CVS Health,CVS Health

In [3]:
df.dropna()

,name,industry,sector,website,rank
0,Walmart,General Merchandisers,Retailing,http://www.walmart.com,1
4,Apple,"Computers, Office Equipment",Technology,http://www.apple.com,1
5,General Motors,Motor Vehicles and Parts,Motor Vehicles & Parts,http://www.gm.com,1
6,Phillips 66,Petroleum Refining,Energy,http://www.phillips66.com,1
7,General Electric,Diversified Financials,Financials,http://www.ge.com,8
8,Ford Motor,Motor Vehicles and Parts,Motor Vehicles & Parts,http://www.ford.com,9
9,CVS Health,CVS Health,CVS Health,CVS Health,CVS Health

In [4]:
df

,name,industry,sector,website,rank
0,Walmart,General Merchandisers,Retailing,http://www.walmart.com,1
1,Exxon Mobil,Petroleum Refining,Energy,http://www.exxonmobil.com,NaN
2,NaN,Petroleum Refining,Energy,http://www.chevron.com,NaN
3,NaN,Insurance: Property and Casualty (Stock),Financials,http://www.berkshirehathaway.com,1
4,Apple,"Computers, Office Equipment",Technology,http://www.apple.com,1
5,General Motors,Motor Vehicles and Parts,Motor Vehicles & Parts,http://www.gm.com,1
6,Phillips 66,Petroleum Refining,Energy,http://www.phillips66.com,1
7,General Electric,Diversified Financials,Financials,http://www.ge.com,8
8,Ford Motor,Motor Vehicles and Parts,Motor Vehicles & Parts,http://www.ford.com,9
9,CVS Health,CVS Health,CVS Health,CVS Health,CVS Health

In [5]:
df.dropna(axis=1)

,industry,sector,website
0,General Merchandisers,Retailing,http://www.walmart.com
1,Petroleum Refining,Energy,http://www.exxonmobil.com
2,Petroleum Refining,Energy,http://www.chevron.com
3,Insurance: Property and Casualty (Stock),Financials,http://www.berkshirehathaway.com
4,"Computers, Office Equipment",Technology,http://www.apple.com
5,Motor Vehicles and Parts,Motor Vehicles & Parts,http://www.gm.com
6,Petroleum Refining,Energy,http://www.phillips66.com
7,Diversified Financials,Financials,http://www.ge.com
8,Motor Vehicles and Parts,Motor Vehicles & Parts,http://www.ford.com
9,CVS Health,CVS Health,CVS Health

In [6]:
df

,name,industry,sector,website,rank
0,Walmart,General Merchandisers,Retailing,http://www.walmart.com,1
1,Exxon Mobil,Petroleum Refining,Energy,http://www.exxonmobil.com,NaN
2,NaN,Petroleum Refining,Energy,http://www.chevron.com,NaN
3,NaN,Insurance: Property and Casualty (Stock),Financials,http://www.berkshirehathaway.com,1
4,Apple,"Computers, Office Equipment",Technology,http://www.apple.com,1
5,General Motors,Motor Vehicles and Parts,Motor Vehicles & Parts,http://www.gm.com,1
6,Phillips 66,Petroleum Refining,Energy,http://www.phillips66.com,1
7,General Electric,Diversified Financials,Financials,http://www.ge.com,8
8,Ford Motor,Motor Vehicles and Parts,Motor Vehicles & Parts,http://www.ford.com,9
9,CVS Health,CVS Health,CVS Health,CVS Health,CVS Health

In [7]:
df.dropna(how='any')

,name,industry,sector,website,rank
0,Walmart,General Merchandisers,Retailing,http://www.walmart.com,1
4,Apple,"Computers, Office Equipment",Technology,http://www.apple.com,1
5,General Motors,Motor Vehicles and Parts,Motor Vehicles & Parts,http://www.gm.com,1
6,Phillips 66,Petroleum Refining,Energy,http://www.phillips66.com,1
7,General Electric,Diversified Financials,Financials,http://www.ge.com,8
8,Ford Motor,Motor Vehicles and Parts,Motor Vehicles & Parts,http://www.ford.com,9
9,CVS Health,CVS Health,CVS Health,CVS Health,CVS Health

In [8]:
df.dropna(axis=1,how='any')

,industry,sector,website
0,General Merchandisers,Retailing,http://www.walmart.com
1,Petroleum Refining,Energy,http://www.exxonmobil.com
2,Petroleum Refining,Energy,http://www.chevron.com
3,Insurance: Property and Casualty (Stock),Financials,http://www.berkshirehathaway.com
4,"Computers, Office Equipment",Technology,http://www.apple.com
5,Motor Vehicles and Parts,Motor Vehicles & Parts,http://www.gm.com
6,Petroleum Refining,Energy,http://www.phillips66.com
7,Diversified Financials,Financials,http://www.ge.com
8,Motor Vehicles and Parts,Motor Vehicles & Parts,http://www.ford.com
9,CVS Health,CVS Health,CVS Health

In [9]:
df=pd.read_csv('C:\\Users\\Junaid Ahmed\\Downloads\\Fortune1000.csv')
df

,name,industry,sector,website,rank
0,Walmart,General Merchandisers,Retailing,http://www.walmart.com,1
1,Exxon Mobil,Petroleum Refining,Energy,http://www.exxonmobil.com,NaN
2,NaN,Petroleum Refining,Energy,http://www.chevron.com,NaN
3,NaN,Insurance: Property and Casualty (Stock),Financials,http://www.berkshirehathaway.com,1
4,Apple,"Computers, Office Equipment",Technology,http://www.apple.com,1
5,General Motors,Motor Vehicles and Parts,Motor Vehicles & Parts,http://www.gm.com,1
6,Phillips 66,Petroleum Refining,Energy,http://www.phillips66.com,1
7,General Electric,Diversified Financials,Financials,http://www.ge.com,8
8,Ford Motor,Motor Vehicles and Parts,Motor Vehicles & Parts,http://www.ford.com,9
9,CVS Health,CVS Health,CVS Health,CVS Health,CVS Health

In [10]:
df.dropna(how='all')

,name,industry,sector,website,rank
0,Walmart,General Merchandisers,Retailing,http://www.walmart.com,1
1,Exxon Mobil,Petroleum Refining,Energy,http://www.exxonmobil.com,NaN
2,NaN,Petroleum Refining,Energy,http://www.chevron.com,NaN
3,NaN,Insurance: Property and Casualty (Stock),Financials,http://www.berkshirehathaway.com,1
4,Apple,"Computers, Office Equipment",Technology,http://www.apple.com,1
5,General Motors,Motor Vehicles and Parts,Motor Vehicles & Parts,http://www.gm.com,1
6,Phillips 66,Petroleum Refining,Energy,http://www.phillips66.com,1
7,General Electric,Diversified Financials,Financials,http://www.ge.com,8
8,Ford Motor,Motor Vehicles and Parts,Motor Vehicles & Parts,http://www.ford.com,9
9,CVS Health,CVS Health,CVS Health,CVS Health,CVS Health

In [11]:
df

,name,industry,sector,website,rank
0,Walmart,General Merchandisers,Retailing,http://www.walmart.com,1
1,Exxon Mobil,Petroleum Refining,Energy,http://www.exxonmobil.com,NaN
2,NaN,Petroleum Refining,Energy,http://www.chevron.com,NaN
3,NaN,Insurance: Property and Casualty (Stock),Financials,http://www.berkshirehathaway.com,1
4,Apple,"Computers, Office Equipment",Technology,http://www.apple.com,1
5,General Motors,Motor Vehicles and Parts,Motor Vehicles & Parts,http://www.gm.com,1
6,Phillips 66,Petroleum Refining,Energy,http://www.phillips66.com,1
7,General Electric,Diversified Financials,Financials,http://www.ge.com,8
8,Ford Motor,Motor Vehicles and Parts,Motor Vehicles & Parts,http://www.ford.com,9
9,CVS Health,CVS Health,CVS Health,CVS Health,CVS Health

In [12]:
df

,name,industry,sector,website,rank
0,Walmart,General Merchandisers,Retailing,http://www.walmart.com,1
1,Exxon Mobil,Petroleum Refining,Energy,http://www.exxonmobil.com,NaN
2,NaN,Petroleum Refining,Energy,http://www.chevron.com,NaN
3,NaN,Insurance: Property and Casualty (Stock),Financials,http://www.berkshirehathaway.com,1
4,Apple,"Computers, Office Equipment",Technology,http://www.apple.com,1
5,General Motors,Motor Vehicles and Parts,Motor Vehicles & Parts,http://www.gm.com,1
6,Phillips 66,Petroleum Refining,Energy,http://www.phillips66.com,1
7,General Electric,Diversified Financials,Financials,http://www.ge.com,8
8,Ford Motor,Motor Vehicles and Parts,Motor Vehicles & Parts,http://www.ford.com,9
9,CVS Health,CVS Health,CVS Health,CVS Health,CVS Health

In [13]:
df=pd.read_csv('C:\\Users\\Junaid Ahmed\\Downloads\\Fortune1000.csv')
df

,name,industry,sector,website,rank
0,Walmart,General Merchandisers,Retailing,http://www.walmart.com,1
1,Exxon Mobil,Petroleum Refining,Energy,http://www.exxonmobil.com,NaN
2,NaN,Petroleum Refining,Energy,http://www.chevron.com,NaN
3,NaN,Insurance: Property and Casualty (Stock),Financials,http://www.berkshirehathaway.com,1
4,Apple,"Computers, Office Equipment",Technology,http://www.apple.com,1
5,General Motors,Motor Vehicles and Parts,Motor Vehicles & Parts,http://www.gm.com,1
6,Phillips 66,Petroleum Refining,Energy,http://www.phillips66.com,1
7,General Electric,Diversified Financials,Financials,http://www.ge.com,8
8,Ford Motor,Motor Vehicles and Parts,Motor Vehicles & Parts,http://www.ford.com,9
9,CVS Health,CVS Health,CVS Health,CVS Health,CVS Health

In [14]:
df.dropna(how='all')

,name,industry,sector,website,rank
0,Walmart,General Merchandisers,Retailing,http://www.walmart.com,1
1,Exxon Mobil,Petroleum Refining,Energy,http://www.exxonmobil.com,NaN
2,NaN,Petroleum Refining,Energy,http://www.chevron.com,NaN
3,NaN,Insurance: Property and Casualty (Stock),Financials,http://www.berkshirehathaway.com,1
4,Apple,"Computers, Office Equipment",Technology,http://www.apple.com,1
5,General Motors,Motor Vehicles and Parts,Motor Vehicles & Parts,http://www.gm.com,1
6,Phillips 66,Petroleum Refining,Energy,http://www.phillips66.com,1
7,General Electric,Diversified Financials,Financials,http://www.ge.com,8
8,Ford Motor,Motor Vehicles and Parts,Motor Vehicles & Parts,http://www.ford.com,9
9,CVS Health,CVS Health,CVS Health,CVS Health,CVS Health

In [26]:
df.dropna(thresh=2)

,name,industry,sector,website,rank
0,Walmart,General Merchandisers,Retailing,http://www.walmart.com,1
4,Apple,"Computers, Office Equipment",Technology,http://www.apple.com,1
5,General Motors,Motor Vehicles and Parts,Motor Vehicles & Parts,http://www.gm.com,1
6,Phillips 66,Petroleum Refining,Energy,http://www.phillips66.com,1
7,General Electric,Diversified Financials,Financials,http://www.ge.com,8
8,Ford Motor,Motor Vehicles and Parts,Motor Vehicles & Parts,http://www.ford.com,9
9,CVS Health,CVS Health,CVS Health,CVS Health,CVS Health

In [16]:
df.dropna(thresh=3)

,name,industry,sector,website,rank
0,Walmart,General Merchandisers,Retailing,http://www.walmart.com,1
1,Exxon Mobil,Petroleum Refining,Energy,http://www.exxonmobil.com,NaN
2,NaN,Petroleum Refining,Energy,http://www.chevron.com,NaN
3,NaN,Insurance: Property and Casualty (Stock),Financials,http://www.berkshirehathaway.com,1
4,Apple,"Computers, Office Equipment",Technology,http://www.apple.com,1
5,General Motors,Motor Vehicles and Parts,Motor Vehicles & Parts,http://www.gm.com,1
6,Phillips 66,Petroleum Refining,Energy,http://www.phillips66.com,1
7,General Electric,Diversified Financials,Financials,http://www.ge.com,8
8,Ford Motor,Motor Vehicles and Parts,Motor Vehicles & Parts,http://www.ford.com,9
9,CVS Health,CVS Health,CVS Health,CVS Health,CVS Health

In [17]:
df=pd.read_csv('C:\\Users\\Junaid Ahmed\\Downloads\\Fortune1000.csv')
df

,name,industry,sector,website,rank
0,Walmart,General Merchandisers,Retailing,http://www.walmart.com,1
1,Exxon Mobil,Petroleum Refining,Energy,http://www.exxonmobil.com,NaN
2,NaN,Petroleum Refining,Energy,http://www.chevron.com,NaN
3,NaN,Insurance: Property and Casualty (Stock),Financials,http://www.berkshirehathaway.com,1
4,Apple,"Computers, Office Equipment",Technology,http://www.apple.com,1
5,General Motors,Motor Vehicles and Parts,Motor Vehicles & Parts,http://www.gm.com,1
6,Phillips 66,Petroleum Refining,Energy,http://www.phillips66.com,1
7,General Electric,Diversified Financials,Financials,http://www.ge.com,8
8,Ford Motor,Motor Vehicles and Parts,Motor Vehicles & Parts,http://www.ford.com,9
9,CVS Health,CVS Health,CVS Health,CVS Health,CVS Health

In [18]:
df.dropna(subset=['name'])

,name,industry,sector,website,rank
0,Walmart,General Merchandisers,Retailing,http://www.walmart.com,1
1,Exxon Mobil,Petroleum Refining,Energy,http://www.exxonmobil.com,NaN
4,Apple,"Computers, Office Equipment",Technology,http://www.apple.com,1
5,General Motors,Motor Vehicles and Parts,Motor Vehicles & Parts,http://www.gm.com,1
6,Phillips 66,Petroleum Refining,Energy,http://www.phillips66.com,1
7,General Electric,Diversified Financials,Financials,http://www.ge.com,8
8,Ford Motor,Motor Vehicles and Parts,Motor Vehicles & Parts,http://www.ford.com,9
9,CVS Health,CVS Health,CVS Health,CVS Health,CVS Health

In [19]:
df.dropna(subset=['rank'])

,name,industry,sector,website,rank
0,Walmart,General Merchandisers,Retailing,http://www.walmart.com,1
3,NaN,Insurance: Property and Casualty (Stock),Financials,http://www.berkshirehathaway.com,1
4,Apple,"Computers, Office Equipment",Technology,http://www.apple.com,1
5,General Motors,Motor Vehicles and Parts,Motor Vehicles & Parts,http://www.gm.com,1
6,Phillips 66,Petroleum Refining,Energy,http://www.phillips66.com,1
7,General Electric,Diversified Financials,Financials,http://www.ge.com,8
8,Ford Motor,Motor Vehicles and Parts,Motor Vehicles & Parts,http://www.ford.com,9
9,CVS Health,CVS Health,CVS Health,CVS Health,CVS Health

In [20]:
df.dropna(inplace=True)

In [21]:
df

,name,industry,sector,website,rank
0,Walmart,General Merchandisers,Retailing,http://www.walmart.com,1
4,Apple,"Computers, Office Equipment",Technology,http://www.apple.com,1
5,General Motors,Motor Vehicles and Parts,Motor Vehicles & Parts,http://www.gm.com,1
6,Phillips 66,Petroleum Refining,Energy,http://www.phillips66.com,1
7,General Electric,Diversified Financials,Financials,http://www.ge.com,8
8,Ford Motor,Motor Vehicles and Parts,Motor Vehicles & Parts,http://www.ford.com,9
9,CVS Health,CVS Health,CVS Health,CVS Health,CVS Health

In [22]:
df=pd.read_csv('C:\\Users\\Junaid Ahmed\\Downloads\\Fortune1000.csv')
df

,name,industry,sector,website,rank
0,Walmart,General Merchandisers,Retailing,http://www.walmart.com,1
1,Exxon Mobil,Petroleum Refining,Energy,http://www.exxonmobil.com,NaN
2,NaN,Petroleum Refining,Energy,http://www.chevron.com,NaN
3,NaN,Insurance: Property and Casualty (Stock),Financials,http://www.berkshirehathaway.com,1
4,Apple,"Computers, Office Equipment",Technology,http://www.apple.com,1
5,General Motors,Motor Vehicles and Parts,Motor Vehicles & Parts,http://www.gm.com,1
6,Phillips 66,Petroleum Refining,Energy,http://www.phillips66.com,1
7,General Electric,Diversified Financials,Financials,http://www.ge.com,8
8,Ford Motor,Motor Vehicles and Parts,Motor Vehicles & Parts,http://www.ford.com,9
9,CVS Health,CVS Health,CVS Health,CVS Health,CVS Health

In [23]:
df.dropna(inplace=True)

In [24]:
df

,name,industry,sector,website,rank
0,Walmart,General Merchandisers,Retailing,http://www.walmart.com,1
4,Apple,"Computers, Office Equipment",Technology,http://www.apple.com,1
5,General Motors,Motor Vehicles and Parts,Motor Vehicles & Parts,http://www.gm.com,1
6,Phillips 66,Petroleum Refining,Energy,http://www.phillips66.com,1
7,General Electric,Diversified Financials,Financials,http://www.ge.com,8
8,Ford Motor,Motor Vehicles and Parts,Motor Vehicles & Parts,http://www.ford.com,9
9,CVS Health,CVS Health,CVS Health,CVS Health,CVS Health

In [ ]:
s